# Header
menu:
  Home: /
  Archives: /archives/
rss: //feeds.feedburner.com/timnewtech/

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- archive
- tagcloud
- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-30567867-1
favicon: true
twitter: timnew
google_plus: 108780866821209046829
fb_admins:
fb_app_id:

recent_posts: 10
