# Header
menu:
  Home: /
  Archives: /archives/
  About Me: /about
rss: /atom.xml 

# Content
excerpt_link: false 
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- archive
- category
- tagcloud
- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
#google_analytics: UA-30567867-1
favicon: true
#google_plus: 108780866821209046829
#fb_admins:
#fb_app_id:

recent_posts: 10
archive_count: 50
index_generator.per_page: 0
