// Generated by CoffeeScript 1.10.0
(function() {
  var categoryRibbonFilter, colorRegex, escape;

  colorRegex = /^\s*(?:\#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]|\#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]|rgba?\(.*\)|hsla?\(.*\))\s*$/;

  categoryRibbonFilter = function(data, callback) {
    var categoryConfig, ref, ribbon;
    if (data.categories == null) {
      return "";
    }
    if (data.ribbon == null) {
      data.ribbon = {};
    }
  
    let t = "";
    let l = "";
    let u = hexo.config.default_category
    if (data.categories.data && data.categories.data[0] && data.categories.data[0].name) {
      t = data.categories.data[0].name
      l = data.categories.data[0].permalink
    } else {
      t = u
    }

    ribbon = data.ribbon;
    ribbon.text = t;
    ribbon.link = l;
  };

  hexo.extend.filter.register('before_post_render', categoryRibbonFilter);

}).call(this);
