// Generated by CoffeeScript 1.10.0
(function() {
  var categoryRibbonFilter, colorRegex, escape;

  colorRegex = /^\s*(?:\#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]|\#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]|rgba?\(.*\)|hsla?\(.*\))\s*$/;

  categoryRibbonFilter = function(data, callback) {
    var categoryConfig, ref, ribbon;
    if (data.categories == null) {
      //return callback();
      return "";
    }
    if (data.ribbon == null) {
      data.ribbon = {};
    }
  
    let t = "";
    let l = "";
    let u = hexo.config.default_category
    if (data.categories.data && data.categories.data[0] && data.categories.data[0].name) {
      t = data.categories.data[0].name
      l = data.categories.data[0].permalink
    } else {
      t = u
    }

    if (typeof data.ribbon === 'string') {
      data.ribbon = {
        text: t
      };
    }
    ribbon = data.ribbon;
    if (ribbon.text == null) {
      ribbon.text = t
      ribbon.link = l
    }
    categoryConfig = (ref = hexo.config.category_ribbon) != null ? ref[ribbon.text] : void 0;
    if (categoryConfig) {
      if (typeof categoryConfig === 'string') {
        if (categoryConfig.match(colorRegex)) {
          ribbon.color = categoryConfig;
        } else {
          ribbon.style = categoryConfig;
        }
      } else {
        ribbon.style = categoryConfig.style;
        ribbon.color = categoryConfig.color;
      }
    } else {
      console.log("Unknown Category: " + ribbon.text);
    }
  };

  hexo.extend.filter.register('before_post_render', categoryRibbonFilter);

}).call(this);
